[build]
  publish = "contrib/build"
  command = "npx parcel build contrib/index.html --out-dir contrib/build"

[[redirects]]
  from = "https://bitters.netlify.com/*"
  to = "https://github.com/thoughtbot/bitters"
  status = 301
  force = true
